name: Build Mod Menu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: mod-menu-artifact
        path: path/to/your/mod-menu/build/output/directory
